skip_docs

platform :android do

  lane :publish_prod do
    # First upload to beta
    upload_to_play_store(
      package_name: "dev.zacsweers.fieldspottr",
      track: "beta", # Open testing
      release_status: "completed", # Auto-publish to beta
      aab: "build/outputs/bundle/release/field-spottr-root-release.aab",
      mapping: "build/outputs/mapping/release/mapping.txt",
      json_key: "release/play-account.json",
      version_code: ENV['FS_VERSION_CODE'],
      version_name: ENV['FS_VERSION_NAME']
    )

    # Then promote to production
    upload_to_play_store(
      package_name: "dev.zacsweers.fieldspottr",
      track: "beta",
      track_promote_to: "production",
      release_status: "completed", # Auto-publish to production
      json_key: "release/play-account.json",
      version_code: ENV['FS_VERSION_CODE'],
      version_name: ENV['FS_VERSION_NAME']
    )
  end

end

platform :ios do
  projects = ["FieldSpottr"]

  ios_bundle_ids = [
    "dev.zacsweers.FieldSpottr",
  ]

  before_all do |lane|
    cleanup_ci_keychain if is_ci
    xcodes(select_for_current_build_only: true)
  end

  after_all do |lane|
    cleanup_ci_keychain if is_ci
  end

  error do |lane, exception|
    cleanup_ci_keychain if is_ci
  end

  lane :certs do |options|
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )
    match(app_identifier: ios_bundle_ids)
  end

  lane :recreate_certs do |options|
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )

    match_nuke(
      app_identifier: ios_bundle_ids,
      type: "appstore"
    )

    match(app_identifier: ios_bundle_ids)
  end

  lane :lint do
    swiftlint(
      mode: :lint,
      raise_if_swiftlint_error: true,
      config_file: ".swiftlint.yml"
    )
  end

  lane :lint_fix do
    swiftlint(
      mode: :fix,
      config_file: ".swiftlint.yml"
    )
  end

  private_lane :build_fs do |options|
    setup_ci if is_ci

    skip_certs = env_nil_or_blank('MATCH_PASSWORD')

    certs(type: 'appstore') unless skip_certs

    increment_build_number(
      xcodeproj: "FieldSpottr/FieldSpottr.xcodeproj",
      build_number: ENV['FS_BUILD_NUMBER']
    ) unless env_nil_or_blank('FS_BUILD_NUMBER')

    build_app(
      project: "FieldSpottr/FieldSpottr.xcodeproj",
      scheme: options[:scheme],
      buildlog_path: "build/fastlane-buildlog",
      skip_package_ipa: skip_certs,
      skip_codesigning: skip_certs
    )
  end

  lane :build_prod do
    build_fs(scheme: "FieldSpottr")
  end

  lane :publish_prod do
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, # if it is enterprise or not
    )

    release_notes = File.read("./release_notes.txt")

    upload_to_testflight(
      app_identifier: "dev.zacsweers.FieldSpottr",
      changelog: release_notes,
      distribute_external: true,
      notify_external_testers: true,
      skip_waiting_for_build_processing: true
    )

    # TODO eventually enable this
    # Submit for App Store review with release notes
#     upload_to_app_store(
#       app_identifier: "dev.zacsweers.FieldSpottr",
#       submit_for_review: true,
#       automatic_release: true,
#       force: true,
#       submission_information: {
#         release_notes: {
#           'en-US' => release_notes
#         }
#       }
#     )
  end

  lane :build do
    build_prod
  end
end

def cleanup_ci_keychain(name = "fastlane_tmp_keychain")
  if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
    puts "CI keychain exists. Deleting it and restoring the default keychain"
    delete_keychain(name: name)
    sh("security default-keychain -s ~/Library/Keychains/login.keychain-db")
  end
end

def env_nil_or_blank(name)
  value = ENV[name]
  return value.nil? || value.empty?
end
